### ISSUE TITLE
Some test case results are incorrectly coded as "Not found" for Asqatasun

### ISSUE THREAD

**Issue by dzc34** [alphagov/accessibility-tool-audit#5]
The following test case results are incorrectly coded as "Not found" for Asqatasun v4.0.3

> "Link contains only a full stop" 

https://alphagov.github.io/accessibility-tool-audit/tests/links-link-contains-only-a-full-stop.html
![selection_003](https://cloud.githubusercontent.com/assets/6709977/23327606/362fb254-fb0f-11e6-9ac3-a45055bac5fa.png)

> "html element has an empty lang attribute"
> "Empty page title" 

https://alphagov.github.io/accessibility-tool-audit/example-pages/empty.html
![selection_004](https://cloud.githubusercontent.com/assets/6709977/23327431/7a2c1112-fb0c-11e6-9e5a-7ccda0a379f4.png)

**Comment by selfthinker** [comment]
Thanks for reporting that. We have now updated the results, which has pushed Asqatasun further up to 29%/43%.
